- type: job
  id: Nomad
  name: job-name-nomad
  description: job-description-nomad
  playTimeTracker: JobNomad
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
  access:
    - Maintenance
