- type: constructionGraph
  id: KitchenMill
  start: start
  graph:
    - node: start
      edges:
        - to: end
          steps:
            - material: WoodPlank
              amount: 4
              doAfter: 2
    - node: end
      entity: KitchenMill

- type: constructionGraph
  id: Campfire
  start: start
  graph:
    - node: start
      edges:
        - to: end
          steps:
            - material: WoodPlank
              amount: 5
              doAfter: 5
    - node: end
      entity: Campfire
