- type: entity
  name: potato
  parent: FoodProduceBase
  id: FoodPotato
  description: A hardy tuber, good for quenching hunger.
  components:
    - type: FlavorProfile
      flavors:
        - potatoes
    - type: SolutionContainerManager
      solutions:
        food:
          maxVol: 14
          reagents:
            - ReagentId: Nutriment
              Quantity: 10
            - ReagentId: Vitamin
              Quantity: 4
    - type: Sprite
      sprite: Objects/Specific/Hydroponics/potato.rsi
    - type: Produce
      seedId: potato
    - type: Extractable
      juiceSolution:
        reagents:
          - ReagentId: JuicePotato
            Quantity: 10
    - type: Tag
      tags:
        - Potato
        - Vegetable
    - type: FoodSequenceElement
      entries:
        Burger: Potato
        Taco: Potato
